---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Index built wheels
  command: "ls -1 {{ repo_build_output }}"
  register: built_wheels
  tags:
    - repo-build-index-wheels
    - repo-create-pool
    - repo-copy-wheels-to-pool
    - repo-create-release-links
    - repo-create-links-index
    - repo-create-release-manifest

- name: Create release process script
  template:
    src: "op-release-script.sh.j2"
    dest: "/opt/op-release-script.sh"
  tags:
    - repo-create-pool

- name: Run release process script
  shell: "bash /opt/op-release-script.sh"
  tags:
    - repo-create-pool

- name: Remove release process script
  file:
    path: "/opt/op-release-script.sh"
    state: absent
  tags:
    - repo-create-pool

- name: Index all manifest wheels
  shell: "ls -1 *.whl"
  args:
    chdir: "{{ repo_build_release_path}}/{{ repo_build_release_tag }}"
  register: manifest_wheels
  tags:
    - repo-index-links
    - repo-create-release-manifest

- name: Create release manifest
  template:
    src: "manifest.in.j2"
    dest: "{{ repo_build_release_path }}/{{ repo_build_release_tag }}/MANIFEST.in"
  tags:
    - repo-create-release-manifest

- name: Create absolute requirements
  template:
    src: "requirements_absolute_requirements.txt.j2"
    dest: "{{ repo_build_release_path }}/{{ repo_build_release_tag }}/requirements_absolute_requirements.txt"
  tags:
    - repo-create-absolute-requirements

- name: Index built wheels
  command: "ls -1 {{ repo_build_release_path }}/{{ repo_build_release_tag }}"
  register: indexed_links
  tags:
    - repo-index-links
    - repo-create-release-index

- name: Create release index
  template:
    src: "release_index_links.html.j2"
    dest: "{{ repo_build_release_path }}/{{ repo_build_release_tag }}/index.html"
  tags:
    - repo-create-release-index

- name: Index general links
  command: "ls -1 {{ repo_build_global_links_path }}"
  register: global_indexed_links
  tags:
    - repo-index-links
    - repo-create-global-release-index

- name: Create release index
  template:
    src: "global_indexed_links.html.j2"
    dest: "{{ repo_build_global_links_path }}/index.html"
  tags:
    - repo-create-global-release-index
