---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Drop Shibboleth Config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ keystone_system_user_name }}"
    group: "{{ keystone_system_group_name }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: "shibboleth-attribute-map.xml.j2", dest: "/etc/shibboleth/attribute-map.xml" }
    - { src: "shibboleth2.xml.j2", dest: "/etc/shibboleth/shibboleth2.xml" }
  notify:
    - Restart Shibd

- name: Generate the Shibboleth SP key-pair
  shell: "shib-keygen -h {{ external_lb_vip_address }} -y {{ keystone_sp.cert_duration_years }}"
  args:
    creates: "/etc/shibboleth/sp-cert.pem"
  when: inventory_hostname == groups['keystone_all'][0]
  notify:
    - Restart service
    - Restart Shibd

- name: Store sp cert
  slurp:
    src: "/etc/shibboleth/sp-cert.pem"
  register: _keystone_sp_cert
  changed_when: false
  when: inventory_hostname == groups['keystone_all'][0]

- name: Store sp key
  slurp:
    src: "/etc/shibboleth/sp-key.pem"
  register: _keystone_sp_key
  changed_when: false
  when: inventory_hostname == groups['keystone_all'][0]

- name: Register a fact for the cert and key
  set_fact:
     keystone_sp_cert_fact: "{{ _keystone_sp_cert.content }}"
     keystone_sp_key_fact: "{{ _keystone_sp_key.content }}"
  when: inventory_hostname == groups['keystone_all'][0]

- name: Distribute sp key
  copy:
    dest: "/etc/shibboleth/sp-key.pem"
    content: "{{ hostvars[groups['keystone_all'][0]]['keystone_sp_key_fact'] | b64decode }}"
    owner: "{{ keystone_system_user_name }}"
    group: "{{ keystone_system_group_name }}"
    mode: "0640"
  when: inventory_hostname != groups['keystone_all'][0]
  notify:
    - Restart service on first node
    - Restart service on other nodes
    - Restart Shibd

- name: Distribute sp cert
  copy:
    dest: "/etc/shibboleth/sp-cert.pem"
    content: "{{ hostvars[groups['keystone_all'][0]]['keystone_sp_cert_fact'] | b64decode }}"
    owner: "{{ keystone_system_user_name }}"
    group: "{{ keystone_system_group_name }}"
    mode: "0640"
  when: inventory_hostname != groups['keystone_all'][0]
  notify:
    - Restart service
    - Restart Shibd

- name: Set appropriate file ownership on the Shibboleth SP key-pair
  file:
    path: "{{ item }}"
    owner: "_shibd"
    group: "_shibd"
  with_items:
    - "/etc/shibboleth/sp-cert.pem"
    - "/etc/shibboleth/sp-key.pem"
  when: inventory_hostname != groups['keystone_all'][0]
  notify:
    - Restart service
    - Restart Shibd
