---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in ironic_developer_constraints %}
      {{ item }}
      {% endfor %}
  when:
    - ironic_developer_mode | bool

- include: ironic_install_apt.yml
  static: no
  when:
    - ansible_pkg_mgr == 'apt'
    - ironic_developer_mode | bool
  vars:
    apt_pkgs: "{{ ironic_developer_mode_distro_packages }}"

- name: Clone requirements git repository
  git:
    repo: "{{ ironic_requirements_git_repo }}"
    dest: "/opt/requirements"
    clone: yes
    update: yes
    version: "{{ ironic_requirements_git_install_branch }}"
  when:
    - ironic_developer_mode | bool

- name: Add constraints to pip_install_options fact for developer mode
  set_fact:
    pip_install_options_fact: "{{ pip_install_options|default('') }} --constraint /opt/developer-pip-constraints.txt --constraint /opt/requirements/upper-constraints.txt"
  when:
    - ironic_developer_mode | bool

- name: Set pip_install_options_fact when not in developer mode
  set_fact:
    pip_install_options_fact: "{{ pip_install_options|default('') }}"
  when:
    - not ironic_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ ironic_requires_pip_packages | join(' ') }}"
    state: latest
    extra_args: "{{ pip_install_options_fact }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Get local venv checksum
  stat:
    path: "/var/cache/{{ ironic_venv_download_url | basename }}"
    get_md5: False
  when:
    - not ironic_developer_mode | bool
  register: local_venv_stat

- name: Get remote venv checksum
  uri:
    url: "{{ ironic_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: True
  when:
    - not ironic_developer_mode | bool
  register: remote_venv_checksum

# TODO: When project moves to ansible 2 we can pass this a sha256sum which will:
#       a) allow us to remove force: yes
#       b) allow the module to calculate the checksum of dest file which would
#          result in file being downloaded only if provided and dest sha256sum
#          checksums differ
- name: Attempt venv download
  get_url:
    url: "{{ ironic_venv_download_url }}"
    dest: "/var/cache/{{ ironic_venv_download_url | basename }}"
    force: yes
  ignore_errors: true
  register: get_venv
  when:
    - not ironic_developer_mode | bool
    - (local_venv_stat.stat.exists == False or
        {{ local_venv_stat.stat.checksum is defined and local_venv_stat.stat.checksum != remote_venv_checksum.content | trim }})

- name: Set ironic get_venv fact
  set_fact:
    ironic_get_venv: "{{ get_venv }}"

- name: Remove existing venv
  file:
    path: "{{ ironic_bin | dirname }}"
    state: absent
  when:
    - ironic_get_venv | changed

- name: Create ironic venv dir
  file:
    path: "{{ ironic_bin | dirname }}"
    state: directory
  register: ironic_venv_dir

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ ironic_venv_download_url | basename }}"
    dest: "{{ ironic_bin | dirname }}"
    copy: "no"
  when:
    - not ironic_developer_mode | bool
    - ironic_get_venv | changed or ironic_venv_dir | changed
  notify: Restart ironic services

- name: Install pip packages
  pip:
    name: "{{ ironic_pip_packages | join(' ') }}"
    state: latest
    virtualenv: "{{ ironic_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: "{{ pip_install_options_fact }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when:
    - ironic_get_venv | failed or ironic_developer_mode | bool
  notify: Restart ironic services

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto {{ ironic_bin | dirname }}
  when:
    - not ironic_developer_mode | bool
    - ironic_get_venv | success
